version: "3.5"

services:
  pico-server:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    command: ["pico", "server"]
    ports:
      - "8080:8080"
    networks:
      - pico-network

  pico-agent-1:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    command:
      - "pico"
      - "agent"
      - "--listeners"
      - "endpoint1/local-app-1:3000"
      - "--server.url"
      - "http://pico-server:8080"
    networks:
      - pico-network

  local-app-1:
    image: python:3.12.2-alpine3.18
    command: ["python3", "-m", "http.server", "3000", "--directory", "/app"]
    volumes:
      - ./endpoint1:/app
    networks:
      - pico-network

  pico-agent-2:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    command:
      - "pico"
      - "agent"
      - "--listeners"
      - "endpoint2/local-app-2:3000"
      - "--server.url"
      - "http://pico-server:8080"
    networks:
      - pico-network

  local-app-2:
    image: python:3.12.2-alpine3.18
    command: ["python3", "-m", "http.server", "3000", "--directory", "/app"]
    volumes:
      - ./endpoint2:/app
    networks:
      - pico-network


networks:
  pico-network:
    driver: bridge
    name: pico-network
